id: setup_docker_continue_codespace_generic
hints:
- Make sure your Codespace has started and is ready to use.
startFlow:
  if:
    conditions:
    - conditionId: user_has_feature_flag
      equals: false
      params:
        featureFlag: 'codespaces'
    then:
      do:
      - actionId: finish_step
    else: 
      do:
      - actionId: bot_message
        params:
          person: head-of-rd
          messages:
          - text: I bet you’re eager to get your hands dirty. Let’s set up your local environment so you can start exploring the system.
            delay: 
          - text: At Anythink, our engineers work with a cloud-hosted IDE called [Github Codespaces](https://docs.github.com/en/codespaces/overview). 
            delay: 2000
          - text: :codeInstruction[[Go ahead and **create your own Codespace**.](https://github.com/codespaces/new?hide_repo_select=true&ref=main&repo=${user.repoId})]{block=true}
            delay: 1300
          - text: Use the default options, and :codeInstruction[**click `Create Codespace` and wait until it boots up**.]{block=true}
            delay: 2000
          - text: Once it's up and ready you can start working directly in the browser or use VS Code to connect to the codespace in the cloud.
            delay: 3000
trigger:
  type: github_codespace_started
  flowNode: 
    if:
      conditions:
      - conditionId: user_has_feature_flag
        params: 
          featureFlag: 'codespaces'
      then:
        do:
        - actionId: bot_message
          params:
            person: head-of-rd
            messages:
            - text: Great! Looks like your Codespace is up and running. 
              delay: 1000
            - text: :instruction[You can now **run \`docker-compose up\` in your codespace's terminal** to load Anythink's backend and frontend.]{block=true}
              delay: 3000
            - text: This should take a few minutes, so hang tight. **I'll let you know when it's done**. 
              delay: 1000
            - text: If you need any help, just reach out to Joebroom, our Support guy, right here in Snack.
              delay: 1000
        - actionId: bot_message
          params:
            person: senior-dev
            messages:
            - text: Hi ${user.firstName} 
              delay: 2000
            - text: Welcome to our happy little ~dysfunctional~ family!
              delay: 2500
            - text: I'm Joebroom, officially transferred from "gray patterns" team to Ness's. Just wanted to introduce myself 😎
              delay: 2700
            - text: https://media.giphy.com/media/Piv9GZi2UBouyyjUxW/giphy.gif
              delay: 2700
            - text: Also, while you do have **[Discord](https://discord.gg/jcHcRB4Dzk)** to help, if things get too complicated, feel free to **:input[ask me anything]{text='My question is:'}**, and I'll try to help.
              delay: 4000
            - text: Oh, and if it's something beyond my paygrade, like a serious bug in the system, you can also **contact support@anythink.family**.
              delay: 2000
        - actionId: finish_step
