id: setup_frontend_docker_generic
learningObjectives:
- Setting up your local environment 
hints:
- run `docker compose up` from the root directory
- make sure the network requests in the client are complete ok using the network tab.
startFlow:
  if:
    conditions:
    - conditionId: user_has_feature_flag
      params:
        featureFlag: 'codespaces'
    then:
      do:
      - actionId: bot_message
        params:
          person: head-of-rd
          messages:
          - text: Now you can go ahead **check the frontend** and make sure it’s **connected
              to the backend**.
            delay: 2500
          - text: :instruction[**Go to https://${user.codespace.name}-3001.preview.app.github.dev**]
            delay: 3800
    else:
      do:
      - actionId: bot_message
        params:
          person: head-of-rd
          messages:
          - text: Now you can go ahead **check the frontend** and make sure it’s **connected
              to the backend**.
            delay: 2500
          - text: :instruction[**Go to http://localhost:3001/**]{block=true}
            delay: 3000
          - text: :instruction[If you encounter a problem, make sure that the `docker-compose up` process has finished running and try again.]{block=true}
            delay: 2000
trigger:
  type: local_page_load
  flowNode:
       do:
        - actionId: bot_message
          params:
            person: head-of-rd
            messages:
            - text: Great, looks like everything is working.
              delay: 2000
        - actionId: finish_step
