id: setup_docker_continue_codespace_generic
hints:
- Make sure your codespace has started and is ready to use.
startFlow:
trigger:
  type: github_codespace_started
  flowNode:
    if:
      conditions:
      - conditionId: user_has_feature_flag
        params:
          featureFlag: 'codespaces'
      then:
        do:
        - actionId: bot_message
          params:
            person: head-of-rd
            messages:
            - text: |-
                Great! Looks like your codespace is up and running. You can now
                **run \`docker-compose up\` in your codespace's terminal** to load Anythink's backend and frontend.
              delay: 3000
        - actionId: finish_step
