id: setup_docker_generic
hints:
- Read through the Docker installation guide thoroughly and make sure you didn't miss
  any steps.
- If you've already installed Docker on your machine, open the application and follow
  the Quick Start Guide. To run the Quick Start Guide on demand, select the Docker
  menu and then choose Quick Start Guide.
- Make sure you ran the \`docker-compose up\` command from the **project root directory**
  and that it finished running. This may take a few moments.
startFlow:
  do:
  - actionId: bot_message
    params:
      person: head-of-rd
      messages:
      - text: "![](https://media.giphy.com/media/l2QE93CiS1hR6WbK0/giphy.gif)"
        delay: 0
      - text: Hey again!
        delay: 1500
      - text: I know that things might feel a bit overwhelming when you start a new
          job.
        delay: 2500
      - text: "So, to help familiarize you with your new work environment, I was thinking
          that maybe you first should set it up. \U0001F60A"
        delay: 3000
      - text: Just **let me know once you’re ready** to start your first task!
        delay: 5000
trigger:
  type: user_message_to_head-of-rd
  flowNode:
    if:
      conditions:
      - conditionId: is_user_message_text_ready_to_continue
      then:
        do:
        - actionId: bot_message
          params:
            person: head-of-rd
            messages:
            - text: Awesome! Oh right, here at ${companyName}, we like to call our
                tasks - 'dibs'.
              delay: 700
            - text: "I wish I could say there's a cool explanation for it, but honestly,
                it's just one of Mr. Ben's weird fixations \U0001F937 "
              delay: 3500
            - text: You'll get it once you meet him; he’s a bit, well, he sure is…
                something.
              delay: 4000
            - text: _Anyway, the DIB!_
              delay: 4000
            - text: Before we dive into the code, we need Docker. It’s going to make
                it easier for us to run things locally, which we’ll have to do a lot
                during your work here.
              delay: 2000
            - text: "**So first thing’s first - [install Docker](https://docs.docker.com/get-docker/).**"
              delay: 5500
            - text: Write me back when you're done. K?
              delay: 3000
        - actionId: finish_step
      else:
        do:
        - actionId: bot_message
          params:
            person: head-of-rd
            messages:
            - text: Umm, If you need any help, just let me know that you’re stuck.
                If that’s not the case - take your time and tell me once you're ready
                :)
              delay: 2000