id: setup_docker_continue_generic
title: Continue setting up your local environment with Anythink
description: |-
  It’s time to set up your development environment.
  Your manager will help you set up Docker locally, which will make it much easier to run our system and all its dependencies.
actionurl: "/chat"
hints:
- Read through the Docker installation guide thoroughly and make sure you didn't miss
  any steps.
- If you've already installed Docker on your machine, open the application and follow
  the Quick Start Guide. To run the Quick Start Guide on demand, select the Docker
  menu and then choose Quick Start Guide.
- Make sure you ran the \`docker-compose up\` command from the **project root directory**
  and that it finished running. This may take a few moments.
isGeneric: true
startBot: head-of-rd
startFlow:
trigger:
  type: user_message_to_head-of-rd
  flowNode:
    if:
      conditions:
      - conditionId: is_user_message_text_ready_to_continue
      then:
        do:
        - actionId: bot_message
          params:
            person: head-of-rd
            messages:
            - text: |-
                Great! You can verify docker is ready by running the following commands in your terminal: \`docker -v\` and \`docker-compose -v\`.
                Then, **run \`docker-compose up\` from the project root directory** to load Anythink's backend and frontend.
              delay: 3000
            - text: Ok. That’s a great first step - now we can make sure that the
                code is working :)
              delay: 2000
        - actionId: finish_step
      else:
        do:
        - actionId: bot_message
          params:
            person: head-of-rd
            messages:
            - text: Umm, If you need any help, just let me know that you’re stuck.
                If that’s not the case - take your time and tell me once you're ready
                :)
              delay: 2000